[workspace]

members = [
  "aggregator",
  "aggregator-test",
  "branches",
  "communicator",
  "functions",
  "generics",
  "guessing_game",
  "hash_map",
  "hello_cargo",
  "ownership",
  "privacy",
  "rectangles",
  "restaurant",
  "slices",
  "structs",
  "variables",
]
